default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: db/write_now_development\

test:
  <<: *default
  database: db/write_now_test\

production:
  <<: *default
  database: write-now_production
  username: write-now
  password: <%= ENV['WRITE-NOW_DATABASE_PASSWORD'] %>